### ISSUE TITLE
Use of Version Tags

### ISSUE THREAD

**Issue by bogacg** [Snowulf/okta-node#5]
Warning people in ReadMe about breaking version changes is good, but using git tags for versioning is a better practice.
Because there are no tags in this repo, people using npm can't understand whats wrong about their app when they clone their code in a different machine and reload modules, this repo will cause problem. In a project dependent to many modules,  finding error will be time consuming.

Thanks for your efforts.

**Comment by ShakataGaNai** [comment]
Project deprecated. Please see [oktajs](https://github.com/Snowulf/oktajs).
